# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: journal/journal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='journal/journal.proto',
  package='huawei.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x15journal/journal.proto\x12\x0chuawei.proto\"I\n\x0bJournalMeta\x12\x0c\n\x04path\x18\x01 \x01(\t\x12,\n\x06status\x18\x02 \x01(\x0e\x32\x1c.huawei.proto.JOURNAL_STATUS\"1\n\rJournalMarker\x12\x13\n\x0b\x63ur_journal\x18\x01 \x01(\t\x12\x0b\n\x03pos\x18\x02 \x01(\x04\"\x87\x01\n\x0eJournalElement\x12\x0f\n\x07journal\x18\x01 \x01(\t\x12\x14\n\x0cstart_offset\x18\x02 \x01(\x04\x12\x12\n\nend_offset\x18\x03 \x01(\x04\x12\x0c\n\x04path\x18\x04 \x01(\t\x12,\n\x06status\x18\x05 \x01(\x0e\x32\x1c.huawei.proto.JOURNAL_STATUS*5\n\x0eJOURNAL_STATUS\x12\x0b\n\x07\x43REATED\x10\x00\x12\n\n\x06OPENED\x10\x01\x12\n\n\x06SEALED\x10\x02\x42\x06\xa2\x02\x03\x44RSb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_JOURNAL_STATUS = _descriptor.EnumDescriptor(
  name='JOURNAL_STATUS',
  full_name='huawei.proto.JOURNAL_STATUS',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CREATED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPENED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEALED', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=303,
  serialized_end=356,
)
_sym_db.RegisterEnumDescriptor(_JOURNAL_STATUS)

JOURNAL_STATUS = enum_type_wrapper.EnumTypeWrapper(_JOURNAL_STATUS)
CREATED = 0
OPENED = 1
SEALED = 2



_JOURNALMETA = _descriptor.Descriptor(
  name='JournalMeta',
  full_name='huawei.proto.JournalMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='huawei.proto.JournalMeta.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='huawei.proto.JournalMeta.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=112,
)


_JOURNALMARKER = _descriptor.Descriptor(
  name='JournalMarker',
  full_name='huawei.proto.JournalMarker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cur_journal', full_name='huawei.proto.JournalMarker.cur_journal', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos', full_name='huawei.proto.JournalMarker.pos', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=163,
)


_JOURNALELEMENT = _descriptor.Descriptor(
  name='JournalElement',
  full_name='huawei.proto.JournalElement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='journal', full_name='huawei.proto.JournalElement.journal', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_offset', full_name='huawei.proto.JournalElement.start_offset', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_offset', full_name='huawei.proto.JournalElement.end_offset', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='huawei.proto.JournalElement.path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='huawei.proto.JournalElement.status', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=301,
)

_JOURNALMETA.fields_by_name['status'].enum_type = _JOURNAL_STATUS
_JOURNALELEMENT.fields_by_name['status'].enum_type = _JOURNAL_STATUS
DESCRIPTOR.message_types_by_name['JournalMeta'] = _JOURNALMETA
DESCRIPTOR.message_types_by_name['JournalMarker'] = _JOURNALMARKER
DESCRIPTOR.message_types_by_name['JournalElement'] = _JOURNALELEMENT
DESCRIPTOR.enum_types_by_name['JOURNAL_STATUS'] = _JOURNAL_STATUS

JournalMeta = _reflection.GeneratedProtocolMessageType('JournalMeta', (_message.Message,), dict(
  DESCRIPTOR = _JOURNALMETA,
  __module__ = 'journal.journal_pb2'
  # @@protoc_insertion_point(class_scope:huawei.proto.JournalMeta)
  ))
_sym_db.RegisterMessage(JournalMeta)

JournalMarker = _reflection.GeneratedProtocolMessageType('JournalMarker', (_message.Message,), dict(
  DESCRIPTOR = _JOURNALMARKER,
  __module__ = 'journal.journal_pb2'
  # @@protoc_insertion_point(class_scope:huawei.proto.JournalMarker)
  ))
_sym_db.RegisterMessage(JournalMarker)

JournalElement = _reflection.GeneratedProtocolMessageType('JournalElement', (_message.Message,), dict(
  DESCRIPTOR = _JOURNALELEMENT,
  __module__ = 'journal.journal_pb2'
  # @@protoc_insertion_point(class_scope:huawei.proto.JournalElement)
  ))
_sym_db.RegisterMessage(JournalElement)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\242\002\003DRS'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
