# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='huawei.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x63ommon.proto\x12\x0chuawei.proto*J\n\x06RESULT\x12\x0f\n\x0b\x44RS_UNKNOWN\x10\x00\x12\n\n\x06\x44RS_OK\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x12\x0f\n\x0bNO_SUCH_KEY\x10\x03*\x8a\x04\n\nStatusCode\x12\x07\n\x03sOk\x10\x00\x12\x12\n\x0esInternalError\x10\x01\x12\x15\n\x11sSnapAlreadyExist\x10\x64\x12\x11\n\rsSnapNotExist\x10\x65\x12\x14\n\x10sSnapPersitError\x10\x66\x12\x19\n\x15sSnapTransactionError\x10g\x12\x14\n\x10sSnapUpdateError\x10h\x12\x19\n\x15sSnapMetaPersistError\x10i\x12\x15\n\x11sSnapCreateDenied\x10j\x12\x19\n\x14sReplicationNotExist\x10\xc9\x01\x12!\n\x1csReplicationMetaPersistError\x10\xcd\x01\x12\x16\n\x11sInvalidOperation\x10\xce\x01\x12\x15\n\x10sReplicateDenied\x10\xcf\x01\x12\x18\n\x13sVolumeAlreadyExist\x10\xac\x02\x12\x14\n\x0fsVolumeNotExist\x10\xad\x02\x12\x1c\n\x17sVolumeMetaPersistError\x10\xb1\x02\x12\x18\n\x13sBackupAlreadyExist\x10\x90\x03\x12\x14\n\x0fsBackupNotExist\x10\x91\x03\x12\x1d\n\x18sBackupNoFullbackupExist\x10\x92\x03\x12\x18\n\x13sBackupCanNotDelete\x10\x93\x03\x12\x18\n\x13sBackupCreateDenied\x10\x94\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_RESULT = _descriptor.EnumDescriptor(
  name='RESULT',
  full_name='huawei.proto.RESULT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DRS_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRS_OK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_ERROR', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_SUCH_KEY', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=30,
  serialized_end=104,
)
_sym_db.RegisterEnumDescriptor(_RESULT)

RESULT = enum_type_wrapper.EnumTypeWrapper(_RESULT)
_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='huawei.proto.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='sOk', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sInternalError', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sSnapAlreadyExist', index=2, number=100,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sSnapNotExist', index=3, number=101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sSnapPersitError', index=4, number=102,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sSnapTransactionError', index=5, number=103,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sSnapUpdateError', index=6, number=104,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sSnapMetaPersistError', index=7, number=105,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sSnapCreateDenied', index=8, number=106,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sReplicationNotExist', index=9, number=201,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sReplicationMetaPersistError', index=10, number=205,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sInvalidOperation', index=11, number=206,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sReplicateDenied', index=12, number=207,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sVolumeAlreadyExist', index=13, number=300,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sVolumeNotExist', index=14, number=301,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sVolumeMetaPersistError', index=15, number=305,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sBackupAlreadyExist', index=16, number=400,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sBackupNotExist', index=17, number=401,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sBackupNoFullbackupExist', index=18, number=402,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sBackupCanNotDelete', index=19, number=403,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sBackupCreateDenied', index=20, number=404,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=107,
  serialized_end=629,
)
_sym_db.RegisterEnumDescriptor(_STATUSCODE)

StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
DRS_UNKNOWN = 0
DRS_OK = 1
INTERNAL_ERROR = 2
NO_SUCH_KEY = 3
sOk = 0
sInternalError = 1
sSnapAlreadyExist = 100
sSnapNotExist = 101
sSnapPersitError = 102
sSnapTransactionError = 103
sSnapUpdateError = 104
sSnapMetaPersistError = 105
sSnapCreateDenied = 106
sReplicationNotExist = 201
sReplicationMetaPersistError = 205
sInvalidOperation = 206
sReplicateDenied = 207
sVolumeAlreadyExist = 300
sVolumeNotExist = 301
sVolumeMetaPersistError = 305
sBackupAlreadyExist = 400
sBackupNotExist = 401
sBackupNoFullbackupExist = 402
sBackupCanNotDelete = 403
sBackupCreateDenied = 404


DESCRIPTOR.enum_types_by_name['RESULT'] = _RESULT
DESCRIPTOR.enum_types_by_name['StatusCode'] = _STATUSCODE


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
