# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: replicate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from journal import journal_pb2 as journal_dot_journal__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='replicate.proto',
  package='huawei.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0freplicate.proto\x12\x0chuawei.proto\x1a\x15journal/journal.proto\"\xb4\x01\n\x0fOperationRecord\x12\x12\n\noperate_id\x18\x01 \x01(\t\x12.\n\x04type\x18\x02 \x01(\x0e\x32 .huawei.proto.ReplicateOperation\x12\x0c\n\x04time\x18\x03 \x01(\x04\x12\x0f\n\x07snap_id\x18\x04 \x01(\t\x12+\n\x06marker\x18\x05 \x01(\x0b\x32\x1b.huawei.proto.JournalMarker\x12\x11\n\tis_synced\x18\x06 \x01(\x08*>\n\x07RepRole\x12\x0f\n\x0bREP_UNKNOWN\x10\x00\x12\x0f\n\x0bREP_PRIMARY\x10\x01\x12\x11\n\rREP_SECONDARY\x10\x02*\x82\x02\n\x12ReplicateOperation\x12\x15\n\x11INVALID_OPERATION\x10\x00\x12\x16\n\x12REPLICATION_CREATE\x10\x01\x12\x16\n\x12REPLICATION_ENABLE\x10\x02\x12\x17\n\x13REPLICATION_DISABLE\x10\x03\x12\x18\n\x14REPLICATION_FAILOVER\x10\x04\x12\x17\n\x13REPLICATION_REVERSE\x10\x05\x12\x15\n\x11REPLICATION_QUERY\x10\x06\x12\x16\n\x12REPLICATION_DELETE\x10\x07\x12\x14\n\x10REPLICATION_TEST\x10\x08\x12\x14\n\x10REPLICATION_LIST\x10\t*\xe5\x01\n\tRepStatus\x12\x0e\n\nREP_UNKNOW\x10\x00\x12\x10\n\x0cREP_CREATING\x10\x01\x12\x10\n\x0cREP_ENABLING\x10\x03\x12\x0f\n\x0bREP_ENABLED\x10\x04\x12\x11\n\rREP_DISABLING\x10\x05\x12\x10\n\x0cREP_DISABLED\x10\x06\x12\x14\n\x10REP_FAILING_OVER\x10\x07\x12\x13\n\x0fREP_FAILED_OVER\x10\x08\x12\x11\n\rREP_REVERSING\x10\t\x12\x10\n\x0cREP_DELETING\x10\x0b\x12\x0f\n\x0bREP_DELETED\x10\x0c\x12\r\n\tREP_ERROR\x10\x14\x62\x06proto3')
  ,
  dependencies=[journal_dot_journal__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_REPROLE = _descriptor.EnumDescriptor(
  name='RepRole',
  full_name='huawei.proto.RepRole',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REP_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REP_PRIMARY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REP_SECONDARY', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=239,
  serialized_end=301,
)
_sym_db.RegisterEnumDescriptor(_REPROLE)

RepRole = enum_type_wrapper.EnumTypeWrapper(_REPROLE)
_REPLICATEOPERATION = _descriptor.EnumDescriptor(
  name='ReplicateOperation',
  full_name='huawei.proto.ReplicateOperation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID_OPERATION', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPLICATION_CREATE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPLICATION_ENABLE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPLICATION_DISABLE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPLICATION_FAILOVER', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPLICATION_REVERSE', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPLICATION_QUERY', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPLICATION_DELETE', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPLICATION_TEST', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPLICATION_LIST', index=9, number=9,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=304,
  serialized_end=562,
)
_sym_db.RegisterEnumDescriptor(_REPLICATEOPERATION)

ReplicateOperation = enum_type_wrapper.EnumTypeWrapper(_REPLICATEOPERATION)
_REPSTATUS = _descriptor.EnumDescriptor(
  name='RepStatus',
  full_name='huawei.proto.RepStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REP_UNKNOW', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REP_CREATING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REP_ENABLING', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REP_ENABLED', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REP_DISABLING', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REP_DISABLED', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REP_FAILING_OVER', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REP_FAILED_OVER', index=7, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REP_REVERSING', index=8, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REP_DELETING', index=9, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REP_DELETED', index=10, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REP_ERROR', index=11, number=20,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=565,
  serialized_end=794,
)
_sym_db.RegisterEnumDescriptor(_REPSTATUS)

RepStatus = enum_type_wrapper.EnumTypeWrapper(_REPSTATUS)
REP_UNKNOWN = 0
REP_PRIMARY = 1
REP_SECONDARY = 2
INVALID_OPERATION = 0
REPLICATION_CREATE = 1
REPLICATION_ENABLE = 2
REPLICATION_DISABLE = 3
REPLICATION_FAILOVER = 4
REPLICATION_REVERSE = 5
REPLICATION_QUERY = 6
REPLICATION_DELETE = 7
REPLICATION_TEST = 8
REPLICATION_LIST = 9
REP_UNKNOW = 0
REP_CREATING = 1
REP_ENABLING = 3
REP_ENABLED = 4
REP_DISABLING = 5
REP_DISABLED = 6
REP_FAILING_OVER = 7
REP_FAILED_OVER = 8
REP_REVERSING = 9
REP_DELETING = 11
REP_DELETED = 12
REP_ERROR = 20



_OPERATIONRECORD = _descriptor.Descriptor(
  name='OperationRecord',
  full_name='huawei.proto.OperationRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operate_id', full_name='huawei.proto.OperationRecord.operate_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='huawei.proto.OperationRecord.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='huawei.proto.OperationRecord.time', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='snap_id', full_name='huawei.proto.OperationRecord.snap_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='marker', full_name='huawei.proto.OperationRecord.marker', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_synced', full_name='huawei.proto.OperationRecord.is_synced', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=237,
)

_OPERATIONRECORD.fields_by_name['type'].enum_type = _REPLICATEOPERATION
_OPERATIONRECORD.fields_by_name['marker'].message_type = journal_dot_journal__pb2._JOURNALMARKER
DESCRIPTOR.message_types_by_name['OperationRecord'] = _OPERATIONRECORD
DESCRIPTOR.enum_types_by_name['RepRole'] = _REPROLE
DESCRIPTOR.enum_types_by_name['ReplicateOperation'] = _REPLICATEOPERATION
DESCRIPTOR.enum_types_by_name['RepStatus'] = _REPSTATUS

OperationRecord = _reflection.GeneratedProtocolMessageType('OperationRecord', (_message.Message,), dict(
  DESCRIPTOR = _OPERATIONRECORD,
  __module__ = 'replicate_pb2'
  # @@protoc_insertion_point(class_scope:huawei.proto.OperationRecord)
  ))
_sym_db.RegisterMessage(OperationRecord)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
