# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volume.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import replicate_pb2 as replicate__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='volume.proto',
  package='huawei.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0cvolume.proto\x12\x0chuawei.proto\x1a\x0freplicate.proto\"d\n\nVolumeMeta\x12&\n\x04info\x18\x01 \x01(\x0b\x32\x18.huawei.proto.VolumeInfo\x12.\n\x07records\x18\x02 \x03(\x0b\x32\x1d.huawei.proto.OperationRecord\"\xf6\x01\n\nVolumeInfo\x12\x0e\n\x06vol_id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12.\n\nvol_status\x18\x03 \x01(\x0e\x32\x1a.huawei.proto.VolumeStatus\x12\x0c\n\x04size\x18\x04 \x01(\x04\x12\x12\n\nrep_enable\x18\x05 \x01(\x08\x12\x10\n\x08rep_uuid\x18\x06 \x01(\t\x12\x14\n\x0cpeer_volumes\x18\x07 \x03(\t\x12#\n\x04role\x18\x08 \x01(\x0e\x32\x15.huawei.proto.RepRole\x12+\n\nrep_status\x18\t \x01(\x0e\x32\x17.huawei.proto.RepStatus*g\n\x0cVolumeStatus\x12\x0f\n\x0bVOL_UNKNOWN\x10\x00\x12\x10\n\x0cVOL_ENABLING\x10\x01\x12\x11\n\rVOL_AVAILABLE\x10\x02\x12\x10\n\x0cVOL_ATTACHED\x10\x03\x12\x0f\n\x0bVOL_DELETED\x10\x04\x62\x06proto3')
  ,
  dependencies=[replicate__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_VOLUMESTATUS = _descriptor.EnumDescriptor(
  name='VolumeStatus',
  full_name='huawei.proto.VolumeStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VOL_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VOL_ENABLING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VOL_AVAILABLE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VOL_ATTACHED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VOL_DELETED', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=398,
  serialized_end=501,
)
_sym_db.RegisterEnumDescriptor(_VOLUMESTATUS)

VolumeStatus = enum_type_wrapper.EnumTypeWrapper(_VOLUMESTATUS)
VOL_UNKNOWN = 0
VOL_ENABLING = 1
VOL_AVAILABLE = 2
VOL_ATTACHED = 3
VOL_DELETED = 4



_VOLUMEMETA = _descriptor.Descriptor(
  name='VolumeMeta',
  full_name='huawei.proto.VolumeMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='huawei.proto.VolumeMeta.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='records', full_name='huawei.proto.VolumeMeta.records', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=147,
)


_VOLUMEINFO = _descriptor.Descriptor(
  name='VolumeInfo',
  full_name='huawei.proto.VolumeInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vol_id', full_name='huawei.proto.VolumeInfo.vol_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='huawei.proto.VolumeInfo.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vol_status', full_name='huawei.proto.VolumeInfo.vol_status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='huawei.proto.VolumeInfo.size', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rep_enable', full_name='huawei.proto.VolumeInfo.rep_enable', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rep_uuid', full_name='huawei.proto.VolumeInfo.rep_uuid', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='peer_volumes', full_name='huawei.proto.VolumeInfo.peer_volumes', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='role', full_name='huawei.proto.VolumeInfo.role', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rep_status', full_name='huawei.proto.VolumeInfo.rep_status', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=396,
)

_VOLUMEMETA.fields_by_name['info'].message_type = _VOLUMEINFO
_VOLUMEMETA.fields_by_name['records'].message_type = replicate__pb2._OPERATIONRECORD
_VOLUMEINFO.fields_by_name['vol_status'].enum_type = _VOLUMESTATUS
_VOLUMEINFO.fields_by_name['role'].enum_type = replicate__pb2._REPROLE
_VOLUMEINFO.fields_by_name['rep_status'].enum_type = replicate__pb2._REPSTATUS
DESCRIPTOR.message_types_by_name['VolumeMeta'] = _VOLUMEMETA
DESCRIPTOR.message_types_by_name['VolumeInfo'] = _VOLUMEINFO
DESCRIPTOR.enum_types_by_name['VolumeStatus'] = _VOLUMESTATUS

VolumeMeta = _reflection.GeneratedProtocolMessageType('VolumeMeta', (_message.Message,), dict(
  DESCRIPTOR = _VOLUMEMETA,
  __module__ = 'volume_pb2'
  # @@protoc_insertion_point(class_scope:huawei.proto.VolumeMeta)
  ))
_sym_db.RegisterMessage(VolumeMeta)

VolumeInfo = _reflection.GeneratedProtocolMessageType('VolumeInfo', (_message.Message,), dict(
  DESCRIPTOR = _VOLUMEINFO,
  __module__ = 'volume_pb2'
  # @@protoc_insertion_point(class_scope:huawei.proto.VolumeInfo)
  ))
_sym_db.RegisterMessage(VolumeInfo)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
